In [23]:
import math
import torch
from torch import nn

def sigmoid(weights: torch.tensor):
    return 1 / (1 + torch.exp(-weights))


In [39]:
class LinearModel_V1(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer_1 = nn.Linear(in_features=3,out_features=10)
        self.linear_layer_2 = nn.Linear(in_features=10,out_features=20)
        self.linear_layer_3 = nn.Linear(in_features=20, out_features=1)

    def forward(self,x):
        return sigmoid(self.linear_layer_3(self.linear_layer_2(self.linear_layer_1(x))))

torch.manual_seed(42)

data_X = torch.rand(100,3)
data_y = torch.randint(0,2,(100,1))

In [38]:
X_train = torch.tensor(data_X[:80], dtype=torch.float32)
y_train = torch.tensor(data_y[:80], dtype=torch.float32)

X_test = torch.tensor(data_X[80:], dtype=torch.float32)
y_test = torch.tensor(data_y[80:], dtype=torch.float32)

/var/folders/nd/ktj6jq715z1dch5hv4rsd1x80000gn/T/ipykernel_59270/2485558411.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train = torch.tensor(data_X[:80], dtype=torch.float32)
/var/folders/nd/ktj6jq715z1dch5hv4rsd1x80000gn/T/ipykernel_59270/2485558411.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train = torch.tensor(data_y[:80], dtype=torch.float32)
/var/folders/nd/ktj6jq715z1dch5hv4rsd1x80000gn/T/ipykernel_59270/2485558411.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test = torch.tensor(data_X[80:], dtype=torch

In [41]:
model_0 = LinearModel_V1()

loss_fn = nn.MSELoss()

optimizer = torch.optim.SGD(params=model_0.parameters(),lr=0.01)

epochs = 80

for x in range(epochs):

    y_pred = model_0(X_train)

    loss = loss_fn(y_pred, y_train)

    optimizer.zero_grad()

    loss.backward()

    optimizer.step()

    if x % 2 == 0:
        print(f'Epoch {x}, Loss: {loss.item()}')

Epoch 0, Loss: 0.25564661622047424
Epoch 2, Loss: 0.25545772910118103
Epoch 4, Loss: 0.2552739977836609
Epoch 6, Loss: 0.2550952434539795
Epoch 8, Loss: 0.2549212872982025
Epoch 10, Loss: 0.25475209951400757
Epoch 12, Loss: 0.25458744168281555
Epoch 14, Loss: 0.2544272840023041
Epoch 16, Loss: 0.2542714476585388
Epoch 18, Loss: 0.2541198432445526
Epoch 20, Loss: 0.2539723515510559
Epoch 22, Loss: 0.25382885336875916
Epoch 24, Loss: 0.2536892592906952
Epoch 26, Loss: 0.25355345010757446
Epoch 28, Loss: 0.2534213364124298
Epoch 30, Loss: 0.2532927989959717
Epoch 32, Loss: 0.2531677484512329
Epoch 34, Loss: 0.25304609537124634
Epoch 36, Loss: 0.2529277205467224
Epoch 38, Loss: 0.25281256437301636
Epoch 40, Loss: 0.2527005672454834
Epoch 42, Loss: 0.2525915503501892
Epoch 44, Loss: 0.25248557329177856
Epoch 46, Loss: 0.25238239765167236
Epoch 48, Loss: 0.2522820830345154
Epoch 50, Loss: 0.2521844506263733
Epoch 52, Loss: 0.2520894706249237
Epoch 54, Loss: 0.25199705362319946
Epoch 56, Loss

In [45]:
for x in X_test:
    print(model_0(x))

tensor([0.4841], grad_fn=<MulBackward0>)
tensor([0.4630], grad_fn=<MulBackward0>)
tensor([0.4576], grad_fn=<MulBackward0>)
tensor([0.4672], grad_fn=<MulBackward0>)
tensor([0.4810], grad_fn=<MulBackward0>)
tensor([0.4419], grad_fn=<MulBackward0>)
tensor([0.4782], grad_fn=<MulBackward0>)
tensor([0.4426], grad_fn=<MulBackward0>)
tensor([0.4448], grad_fn=<MulBackward0>)
tensor([0.4618], grad_fn=<MulBackward0>)
tensor([0.5173], grad_fn=<MulBackward0>)
tensor([0.4428], grad_fn=<MulBackward0>)
tensor([0.4800], grad_fn=<MulBackward0>)
tensor([0.4663], grad_fn=<MulBackward0>)
tensor([0.4790], grad_fn=<MulBackward0>)
tensor([0.5201], grad_fn=<MulBackward0>)
tensor([0.4769], grad_fn=<MulBackward0>)
tensor([0.4775], grad_fn=<MulBackward0>)
tensor([0.4756], grad_fn=<MulBackward0>)
tensor([0.4764], grad_fn=<MulBackward0>)
