
# **`torch.unsqueeze()` Summary**

### **Definition**

```python
torch.unsqueeze(input, dim) → Tensor
```

Returns a new tensor with a dimension of size `1` inserted at the specified position `dim`.

---

# 1. Parameters

| Parameter | Description                                                                                                     |
| --------- | --------------------------------------------------------------------------------------------------------------- |
| `input`   | The input tensor.                                                                                               |
| `dim`     | The index at which to insert the new dimension. <br> - Can be negative (e.g., `-1` means “last dimension + 1”). |

---

# 2. Return Value

* A **view** of the original tensor (no data copy).
* The shape has one extra dimension of size `1`.

---

# 3. Examples

### Example 1: Basic usage

```python
import torch

x = torch.tensor([1, 2, 3, 4])   # shape: (4,)
y = torch.unsqueeze(x, 0)        # add at dim=0
print(y.shape)                   # torch.Size([1, 4])
print(y)
# tensor([[1, 2, 3, 4]])
```

---

### Example 2: Add at the end

```python
z = torch.unsqueeze(x, -1)       # add at last dim
print(z.shape)                   # torch.Size([4, 1])
print(z)
# tensor([[1],
#         [2],
#         [3],
#         [4]])
```

---

### Example 3: Multiple insertions

```python
x = torch.tensor([1, 2, 3])
y = x.unsqueeze(0).unsqueeze(2)  # add at dim=0, then dim=2
print(y.shape)                   # torch.Size([1, 3, 1])
```

---

### Example 4: Negative indices

```python
x = torch.tensor([1, 2, 3])      # shape (3,)
y = torch.unsqueeze(x, -1)       # add at end
print(y.shape)                   # torch.Size([3, 1])
```

---

# 4. Real-World Use Cases

### a) Preparing input for models

Most models expect inputs with a **batch dimension**:

```python
img = torch.rand(28, 28)         # shape (28,28)
img = img.unsqueeze(0)           # shape (1,28,28) → batch of size 1
```

---

### b) Broadcasting

Align dimensions for operations:

```python
x = torch.tensor([1, 2, 3])      # shape (3,)
y = torch.tensor([[10], [20]])   # shape (2,1)

x = x.unsqueeze(0)               # shape (1,3)
result = x + y                   # shape (2,3)
print(result)
```

---

### c) Expanding channels

```python
gray = torch.rand(64, 64)        # single-channel image
gray = gray.unsqueeze(0)         # shape (1,64,64) → now it has a channel dimension
```

---

# 5. Compare with `.view()` and `.reshape()`

You could also reshape manually, but `unsqueeze` is **cleaner & safer**:

```python
x = torch.tensor([1, 2, 3])
print(x.view(1, 3).shape)        # (1,3) → same as unsqueeze(0)
print(x.view(3, 1).shape)        # (3,1) → same as unsqueeze(1)
```

---

# 6. Compare with `squeeze()`

| Function         | Purpose                         | Example          |
| ---------------- | ------------------------------- | ---------------- |
| `unsqueeze(dim)` | Adds a dimension of size `1`    | `(3,)` → `(1,3)` |
| `squeeze(dim)`   | Removes a dimension if size `1` | `(1,3)` → `(3,)` |

---



# Quick Summary Table

| Code              | Input Shape | Output Shape | Notes                       |
| ----------------- | ----------- | ------------ | --------------------------- |
| `x.unsqueeze(0)`  | `(N,)`      | `(1, N)`     | Add at front (batch dim)    |
| `x.unsqueeze(1)`  | `(N,)`      | `(N, 1)`     | Add at second axis          |
| `x.unsqueeze(-1)` | `(N,)`      | `(N, 1)`     | Add at end                  |
| `x.unsqueeze(-2)` | `(N,)`      | `(1, N)`     | Same as dim=0 for 1D tensor |


In [48]:
import torch

torch.manual_seed(13)

matrix = torch.randn(3,2)

In [49]:
matrix

tensor([[-0.1117, -1.1456],
        [ 1.4103,  1.3654],
        [ 1.1206, -0.9622]])

In [50]:
matrix_2 = torch.randint(low = 0, high = 100,size = (3,2))

In [51]:
matrix_2

tensor([[60,  6],
        [94, 26],
        [42,  9]])

In [52]:
matrix_2_unsqueezed_0 = matrix_2.unsqueeze(0)

In [53]:
matrix_2_unsqueezed_0

tensor([[[60,  6],
         [94, 26],
         [42,  9]]])

In [54]:
matrix_2_unsqueezed_1 = matrix_2.unsqueeze(1)

In [55]:
matrix_2_unsqueezed_1

tensor([[[60,  6]],

        [[94, 26]],

        [[42,  9]]])



<br><br>

